version: '3'

services:
  app:
    image: tcg-simulator/app:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    # command: yarn start --port ${PORT}
    environment:
     - "PORT=${PORT}"
