version: '3'

services:
  app:
    image: tcg-simulator/app:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    # command: bash -c ". ~/.nvm/nvm.sh && yarn start --port ${PORT}"
    environment:
     - "PORT=${PORT}"
