export const deckList = [
  {
    name: "墓地退化【2021/12・オリジナル】",
    url: "https://gachi-matome.com/deckrecipe-detail-dm/?tcgrevo_deck_maker_deck_id=ea1f26a4-6fa4-488b-876a-342575573b52",
    cards: [
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239809_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239809_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239809_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239809_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73709573_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73709573_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73709573_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73709573_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100040512_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100040512_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100040512_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100040512_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100195329_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100195329_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100195329_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100195329_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248020_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248020_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248020_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100248020_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201140_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247675_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247675_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247675_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247675_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73709944_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73709944_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239800_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239800_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207134_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207134_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246238_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100233392_1.jpg",
      },
    ],
  },
  {
    name: "赤単我我我ブランド【2021/12・オリジナル】",
    url: "https://gachi-matome.com/deckrecipe-detail-dm/?tcgrevo_deck_maker_deck_id=a4c9f4ea-0c42-4c7b-987b-a589f549f1d8",
    cards: [
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73712593_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73712593_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73712593_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73712593_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238183_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238183_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238183_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238183_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100053416_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100053416_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100053416_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100127937_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100127937_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100127937_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239665_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239665_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239665_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100239665_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246820_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246820_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246820_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246820_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100238174_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247714_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247714_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101012_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100056359_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100056359_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100056359_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100237667_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100237667_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100237667_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100237667_1.jpg",
      },
    ],
  },
  {
    name: "4cガイアッシュ覇道【2021/12・オリジナル】",
    url: "https://gachi-matome.com/deckrecipe-detail-dm/?tcgrevo_deck_maker_deck_id=da3e7dfb-948e-47d8-8924-d277368ca399",
    cards: [
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013205_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013205_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013205_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013205_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242350_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242350_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242350_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242350_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100250042_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100250042_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100250042_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100250042_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100233368_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100233368_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100233368_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100233368_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242365_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242365_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242365_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100242365_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247672_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247672_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247672_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247672_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100165905_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100165905_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100165905_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100067551_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100067551_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100067551_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100168788_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100168788_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100032148_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100032148_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73713462_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100024985_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247669_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100036487_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100040296_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100036475_1.jpg",
      },
    ],
  },
  {
    name: "ジョー星ゼロルピア【2021/12・オリジナル】",
    url: "https://gachi-matome.com/deckrecipe-detail-dm/?tcgrevo_deck_maker_deck_id=cef7c434-dce8-4e88-915e-f76e23bfdf3c",
    cards: [
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100018278_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100018278_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246655_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246655_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100246655_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100012156_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100050464_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card73709546_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201083_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201083_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201083_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201083_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100011680_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100011680_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100011680_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100011680_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100196934_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201101_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201101_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201101_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100201101_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100219626_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100168737_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100168737_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100168737_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100168737_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100229252_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100229252_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100229252_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100014640_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100225916_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100225916_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100225916_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207287_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207287_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207287_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207287_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100059370_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207134_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100207134_1.jpg",
      },
    ],
  },
  {
    name: "デアリガズ墓地ソース【2021/12・オリジナル】",
    url: "https://gachi-matome.com/deckrecipe-detail-dm/?tcgrevo_deck_maker_deck_id=a7aa7e2f-f2af-4271-b5d1-08ddaee92362",
    cards: [
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100005078_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100005078_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100005078_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100005078_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100025060_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100025060_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100025060_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100025060_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100225934_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100225934_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100225934_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100225934_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100064880_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100064880_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100064880_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100064880_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247987_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247987_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247987_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100247987_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100142202_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100142202_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100142202_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100142202_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013184_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013184_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013184_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100013184_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100196829_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100196829_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100196829_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100189311_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100189311_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100189311_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101075_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101075_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100171905_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100171905_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100101012_1.jpg",
      },
      {
        imageUrl:
          "https://storage.googleapis.com/ka-nabell-card-images/img/card/card100012542_1.jpg",
      },
    ],
  },
];
